## Proteome analisys from NCBI mHipAmp2.hap2 reference Genome

## Load proteome .faa file from NCBI genome reeplace PATH_TO/protein.faa fopr your actual file
hippo_fastap <- "~/Hippo/ncbi_dataset/data/GCF_030028045.1/protein.faa"

## Load the proteome as string set
protein_sequences <- readAAStringSet(fastap)

## Extrac protein names from proteome
sequence_names <- names(protein_sequences)

## Immunity related list of terms
terms <- c("A2M", "ADAR", "^Ago", "^AIM", "^AIRE ", "Akirin", "ALR", "Alpha-2-macroglobulin", "Ankyrin", "Antibacterial", "Antibiotic", "Antigen", "Antimicrobial", "AP-1", "Arabinose-binding", "Argonaut", "Artemis", "ATF", "Autoimmune", "B2M", "Bacterial", "Bactericidal", "B[- ]cell", "BCR", "Beta-2-microglobulin", "Bradykinin", "^C1", "^C2", "^C3", "^C4", "^C5", "^C6", "^C7", "^C8", "^C-type", "CAM ", "CARD", "Caspase", "C-C", "^CD1 ", "CD3 ", "CD4 ", "CD8 ", "CD16 ", "CD28 ", "CD36", "CD40", "CD45", "CD56", "CD79", "CD80", "CD86", "CD94", "CD152", "CETP", "Chemokine", "Clathrin", "CLEC", "CLR", "Coagulation", "Complement[- ,]", "Colony", "CSF", "CTL", "C-X-C", "Cytokine", "Cytolysin", "Cytotoxic", "Cytotoxicity", "Damage", "DAMP", "Db1[- ,]", "DCLRE1C", "DEAD", "Death", "Defesin", "DEXD/H", "Dicer", "Drosha", "DSCAM", "^ERK", "Erythrocyte", "Erythroid", "FA58C", "FcR", "Fibrinogen", "Fibronectin", "FIIND", "flg", "FN3", "FNIII", "forkhead.*box", "FOS", "Fucose-binding", "Fungal", "Galactose-binding", "GFRCR", "Glucoside.*hydrolase", "GPCR", "Granulocyte", "Granzyme", "Heat.*Shock", "Hematopietic", "Histamine", "Histocompatibility", "HLA", "HSP", "IFN", "^IgA", "^IgD", "^IgE", "^IgG", "^IgM", "IKB", "IKK", "^IL", "Immun", "Immune", "Immunity", "Immunoglobulin", "INF", "Integrin", "Interferon", "Interleukin", "IRAK", "IRG", "^IPT[- ,_]", "IPS[- ,]", "ITAM[- ,_]", "ITIM[- ,_]", "JAK", "JNK", "JUN[- ,_]", "Kallikrein", "Kazal", "Killer.*Cell", "KIR", "LBP", "LDL", "Lectin", "Leucine.*Rich", "LGP", "Lipopolysaccharide", "Lipoprotein", "Litaf", "LRR", "Lymphocyte", "Lymphoid", "Lyzozyme", "Macrophage", "Mannose-binding", "MAP K", "MAPK", "Mastocyte", "Mayor.*Histocompatibility", "^MBL", "MDA5", "Megakaryocyte", "Melanin", "MHC", "Mitogen", "Monocyte", "^MUC", "Muramic", "Myco", "MyD88", "Myeloid", "NACHT", "Natural.*Killer", "NB.*ARC", "NFAT", "NF.*Kappa", "NFKB", "NF-Y", "NID-", "NIDO", "NKAP", "NKG", "NKR", "NLR", "NOD", "OAS", "PACT", "PAMP", "PARP", "Pathogen", "Permeability", "Peptidoglycan", "Perforin", "PGB", "PGRP", "Platelet", "Properdin", "PTP", "PYD", "Ras[- ,_]", "RBL", "Retinoic", "Rhamnose-binding", "^Rho[- ,_]", "RIG-I", "^RIP", "RLR[- ,_]", "SAM[- ,_]", "Scavenger", "SEFIR", "Serine.*Protease", "SH2", "SH3", "SPINK", "Spondin", "^STAT", "Sushi", "T[- ]cell", "TCR", "TGF", "Threalose-binding", "Thrombin", "TIL", "TIR", "TLD", "TNF", "Toll[/-]", "Tox-", "Toxin", "TRADD", "TRAF[- ,_]", "TRAIP", "TRBP", "Tumor", "V(D)J", "Viral", "Viric", "Virus", "Willebrand")

terms_names <- c("A2M", "ADAR", "Ago", "AIM", "AIRE", "Akirin", "ALR", "Alpha2", "Ankyrin", "Antibacterial", "Antibiotic", "Antigen", "Antimicrobial", "AP-1", "Arabinose_binding", "Argonaut", "Artemis", "ATF", "Autoimmune", "B2M", "Bacterial", "Bactericidal", "Bcell", "BCR", "Beta2", "Bradykinin", "C1", "C2", "C3", "C4", "C5", "C6", "C7", "C8", "C-type", "CAM", "CARD", "Caspase", "CCL/LR", "CD1 ", "CD3", "CD4", "CD8", "CD16", "CD28", "CD36", "CD40", "CD45", "CD56", "CD79", "CD80", "CD86", "CD94", "CD152", "CETP", "Chemokine", "Clathrin", "CLEC", "CLR", "Coagulation", "Complement", "Colony", "CSF", "CTL", "CXCL/LR", "Cytokine", "Cytolysin", "Cytotoxic", "Cytotoxicity", "Damage", "DAMP", "Db1", "DCLRE1C", "DEAD", "Death", "Defesin", "DEXD/H", "Dicer", "Drosha", "DSCAM", "ERK", "Erythrocyte", "Erythroid", "FA58C", "FcR", "Fibrinogen", "Fibronectin", "FIIND", "flg", "FN3", "FNIII", "forkhead_box", "FOS", "Fucose_binding", "Fungal", "Galactose_binding", "GFRCR", "Glucoside.*hydrolase", "GPCR", "Granulocyte", "Granzyme", "Heat_Shock", "Hematopoietic", "Histamine", "Histocompatibility", "HLA", "HSP", "IFN", "IgA", "IgD", "IgE", "IgG", "IgM", "IKB", "IKK", "IL", "Immun", "Immune", "Immunity", "Immunoglobulin", "INF", "Integrin", "Interferon", "Interleukin", "IRAK", "IRG", "IPT", "IPS", "ITAM", "ITIM", "JAK", "JNK", "JUN", "Kallikrein", "Kazal", "Killer_Cell", "KIR", "LBP", "LDL", "Lectin", "Leucine_Rich", "LGP", "Lipopolysaccharide", "Lipoprotein", "Litaf", "LRR", "Lymphocyte", "Lymphoid", "Lyzozyme", "Macrophage", "Mannose_binding", "MAP_K", "MAPK", "Mastocyte", "Mayor_Histocompatibility", "MBL", "MDA5", "Megakaryocyte", "Melanin", "MHC", "Mitogen", "Monocyte", "MUC", "Muramic", "Myco", "MyD88", "Myeloid", "NACHT", "Natural_Killer", "NB_ARC", "NFAT", "NF_Kappa", "NFKB", "NF-Y", "NID", "NIDO", "NKAP", "NKG", "NKR", "NLR", "NOD", "OAS", "PACT", "PAMP", "PARP", "Pathogen", "Permeability", "Peptidoglycan", "Perforin", "PGB", "PGRP", "Platelet", "Properdin", "PTP", "PYD", "Ras", "RBL", "Retinoic", "Rhamnose_binding", "Rho", "RIG-I", "^RIP", "RLR", "SAM", "Scavenger", "SEFIR", "Serine_Protease", "SH2", "SH3", "SPINK", "Spondin", "^STAT", "Sushi", "Tcell", "TCR", "TGF", "Threalose_binding", "Thrombin", "TIL", "TIR", "TLD", "TNF", "Toll", "Tox", "Toxin", "TRADD", "TRAF", "TRAIP", "TRBP", "Tumor", "VDJ", "Viral", "Viric", "Virus", "Willebrand")

## Function to extract sequence names containing relevant names
Hippo_matching_sequences <- list()
for (i in seq_along(terms)) {
  term <- terms[i]
  term_name <- terms_names[i]
  Hippo_matching_names <- Hippo_sequence_names[grepl(term, Hippo_sequence_names, ignore.case = TRUE)]
  if (length(Hippo_matching_names) > 0) {
    Hippo_matching_sequences[[term_name]] <- list(
      matches = Hippo_matching_names,
      count = length(Hippo_matching_names)
    )
  }
}
